plugins {
    id 'java-library'
}

group 'defence-tower-plugin'
version '1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    compileOnly "com.github.Anuken.Mindustry:core:v160"
    compileOnly "com.github.Anuken.Arc:arc-core:v160"

    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.assertj:assertj-core:3.25.3'
    testImplementation "com.github.Anuken.Mindustry:core:v160"
    testImplementation "com.github.Anuken.Arc:arc-core:v160"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

jar {
    archiveFileName = "tower-defence-plugin.jar"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

