plugins {
    id 'java-library'
}

group 'defence-tower-plugin'
version '1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    compileOnly "com.github.Anuken.Mindustry:core:v160"
    compileOnly "com.github.Anuken.Arc:arc-core:v160"
}

jar {
    archiveFileName = "tower-defence-plugin.jar"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.register('cleanTargetDir', Delete) {
    delete "C:/Games/Mindustry/server/config/mods/tower-defence-plugin.jar"
}

tasks.register('deployJar', Copy) {
    dependsOn jar
    from jar.archiveFile
    into "C:/Games/Mindustry/server/config/mods"
}

jar.finalizedBy(deployJar)
